const express = require('express');
const db = require('../config/database');
const { authenticateToken } = require('./auth');
const PDFDocument = require('pdfkit');

const router = express.Router();

// Generate compliance report PDF
router.get('/compliance/pdf', authenticateToken, async (req, res) => {
  try {
    // Fetch compliance data
    const complianceRes = await db.query(
      `SELECT * FROM compliance_items ORDER BY category`
    );

    const auditRes = await db.query(
      `SELECT COUNT(*) as total_actions FROM audit_logs`
    );

    const filesRes = await db.query(
      `SELECT COUNT(*) as total_files FROM files`
    );

    const breachRes = await db.query(
      `SELECT COUNT(*) as total_breaches FROM breaches`
    );

    const complianceItems = complianceRes.rows;
    const totalActions = auditRes.rows[0].total_actions;
    const totalFiles = filesRes.rows[0].total_files;
    const totalBreaches = breachRes.rows[0].total_breaches;

    // Create PDF
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50
    });

    // Set response headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="compliance-report.pdf"');

    // Pipe to response
    doc.pipe(res);

    // Title
    doc.fontSize(24).font('Helvetica-Bold').text('DPDP Compliance Report', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('Digital Personal Data Protection Act', { align: 'center' });
    doc.moveDown(0.5);

    // Date
    doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(1);

    // Executive Summary
    doc.fontSize(14).font('Helvetica-Bold').text('Executive Summary', { underline: true });
    doc.fontSize(11).font('Helvetica');
    doc.text(`Total Compliance Items: ${complianceItems.length}`);
    doc.text(`Completed Items: ${complianceItems.filter(c => c.completed).length}`);
    doc.text(`Compliance Score: ${Math.round((complianceItems.filter(c => c.completed).length / complianceItems.length) * 100)}%`);
    doc.text(`Total Files: ${totalFiles}`);
    doc.text(`Audit Actions: ${totalActions}`);
    doc.text(`Security Breaches Reported: ${totalBreaches}`);
    doc.moveDown(1);

    // Compliance Checklist
    doc.fontSize(14).font('Helvetica-Bold').text('Compliance Checklist', { underline: true });
    doc.moveDown(0.5);

    // Group by category
    const categories = {};
    complianceItems.forEach(item => {
      if (!categories[item.category]) {
        categories[item.category] = [];
      }
      categories[item.category].push(item);
    });

    doc.fontSize(11).font('Helvetica');
    Object.keys(categories).forEach(category => {
      doc.fontSize(12).font('Helvetica-Bold').text(category);
      categories[category].forEach(item => {
        const status = item.completed ? '✓' : '○';
        doc.fontSize(10).font('Helvetica').text(`  ${status} ${item.title}`);
      });
      doc.moveDown(0.3);
    });

    doc.moveDown(1);

    // Security Metrics
    doc.fontSize(14).font('Helvetica-Bold').text('Security Metrics', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    doc.text(`Immutable Audit Logs: ✓ Enabled`);
    doc.text(`File Encryption: ✓ HTTPS`);
    doc.text(`User Authentication: ✓ JWT Tokens`);
    doc.text(`Data PII Detection: ✓ Automatic Scanning`);
    doc.moveDown(1);

    // Recommendations
    doc.fontSize(14).font('Helvetica-Bold').text('Recommendations', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).font('Helvetica');
    
    const incompleteItems = complianceItems.filter(c => !c.completed);
    if (incompleteItems.length > 0) {
      doc.text(`Priority: Complete remaining ${incompleteItems.length} compliance items:`);
      incompleteItems.slice(0, 5).forEach(item => {
        doc.text(`  • ${item.title}`);
      });
    } else {
      doc.text(`✓ All compliance items completed. Continue regular audits.`);
    }

    doc.moveDown(1);

    // Footer
    doc.fontSize(9).font('Helvetica').text(
      'This report is generated by the DPDP Compliance Platform and reflects the current compliance status.',
      { align: 'center', color: '#666' }
    );

    // Finalize PDF
    doc.end();

  } catch (error) {
    console.error('Error generating PDF:', error);
    res.status(500).json({ error: error.message });
  }
});

// Generate audit trail report PDF
router.get('/audit-trail/pdf', authenticateToken, async (req, res) => {
  try {
    const result = await db.query(
      `SELECT al.*, u.username
       FROM audit_logs al
       JOIN users u ON al.user_id = u.id
       ORDER BY al.created_at DESC
       LIMIT 100`
    );

    const logs = result.rows;

    // Create PDF
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50
    });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="audit-trail-report.pdf"');

    doc.pipe(res);

    // Title
    doc.fontSize(24).font('Helvetica-Bold').text('Audit Trail Report', { align: 'center' });
    doc.fontSize(12).font('Helvetica').text('Complete Activity History', { align: 'center' });
    doc.moveDown(0.5);

    doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(1);

    // Summary
    doc.fontSize(12).font('Helvetica-Bold').text('Summary');
    doc.fontSize(11).font('Helvetica');
    doc.text(`Total Actions: ${logs.length}`);
    doc.text(`Date Range: Last 100 actions`);
    doc.moveDown(1);

    // Audit logs table
    doc.fontSize(12).font('Helvetica-Bold').text('Recent Activities');
    doc.moveDown(0.5);

    doc.fontSize(9).font('Helvetica');
    logs.forEach(log => {
      const date = new Date(log.created_at).toLocaleString();
      const action = log.action.replace(/_/g, ' ');
      doc.text(`${date} | ${action} | ${log.username}`);
    });

    doc.moveDown(1);

    doc.fontSize(9).font('Helvetica').text(
      'This audit trail is immutable and maintained for compliance purposes.',
      { align: 'center', color: '#666' }
    );

    doc.end();

  } catch (error) {
    console.error('Error generating audit PDF:', error);
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
